var newContentArray = [];
var contentArray = [];

function update(id, num, open) {
	"use strict";
	if (open === true) {
		document.getElementById(id).innerHTML = newContentArray[num];
		}
		else if (open === false) {
			document.getElementById(id).innerHTML = contentArray[num];
		}
}


newContentArray[0] = "<p><strong>In 1897 Ivan  Pavlov</strong> (pictured below) published the results of an experiment on conditioning after originally studying digestion in dogs.</p><p>" + '<img src="images/pavlovImg.jpg" alt="dog" width="320" style="padding:10px;">' + "<p>For the purpose of the study he set up a series of contraptions, including and observation screen, a tube for collection of saliva, and straps to hold the dogs in place. This would allow him to observe the dogs reaction to food, and collect its saliva to estimate it’s amounts. A representation of this process can be seen in the picture below.</p>" + '<img src="images/pavlov.jpg" alt="dog" width="320" style="padding:10px;"> </p><p>Ivan Pavlov was looking at salivation in dogs in response to being fed, when he noticed that his dogs would begin to salivate whenever he entered the room, even when he was not bringing them food.<p>Pavlov started from the idea that there are some things that a dog does not need to learn. For example, dogs don’t learn to salivate whenever they see food. This reflex is ‘hard wired’ into the dog, an unconditioned response.</p><p>Then Pavlov discovered that any object or event which the dogs learnt to associate with food (himself, for example) would trigger the same response. </p><p>He came to a conclusion that this behaviour was something they learned, because at an older point in time the dogs did not show this behaviour, and there came a point where they started. He concluded that this type of behaviour change must be the result of learning. He called this the conditioned response.</p><p>After studying all of these factors, Pavlov realized that he had made an important scientific discovery. This led him to devote the rest of his career to studying this type of learning, as seen in the video below.</p>' + '<iframe style="padding:10px;" width="330" height="248" src="//www.youtube.com/embed/hhqumfpxuzI" frameborder="0" allowfullscreen></iframe>' + "</p><button onclick=" +'"update('+"'bubble1',"+"'0',"+'false)"'+">Close</button>";
newContentArray[1] = "<p><strong>Edward Thorndike</strong> (1874 - 1949) is renowned in psychology for his work on learning theory. His work eventually led to the development the idea of <strong>operant conditioning</strong> (education through reinforcement) within behaviourism.</p><p>He extensively studied learning in animals (usually cats).  He developed a classic experiment in which he used a puzzle box to test the laws of learning.</p><p>" + '<iframe style="padding:10px;"width="330" height="248" src="//www.youtube.com/embed/BDujDOLre-8" frameborder="0" allowfullscreen></iframe> </p><p>' +"In this experiment he placed a cat in the puzzle box. Cat had encouragement to escape the cage in the form of a scrap of fish outside. Inside the cage was a lever that could be used to open the cage. Thorndike would time how long it took for the cats to figure out a way out of the cage.</p><p>After the cats had eventually stumbled upon the lever and escaped the cage, they would be put in again, and once more the time it took to escape was noted.  In successive trials the cats would learn that pressing the lever would have favorable consequences and they would adopt this behavior, becoming increasingly quick escaping the cage.</p><p> This led Thorndike to put forward the <strong>&quot;Law of effect&quot; (1905)</strong>, which stated that any behavior that is followed by pleasant consequences is likely to be repeated, and any behavior followed by unpleasant consequences is likely to be stopped."+ "</p><button onclick="+'"update(' + "'bubble2',"+"'1',"+'false)"'+">Close</button>";
newContentArray[2] = "<p><strong>John Broadus Watson</strong> was an American psychologist who launched and was promoting the behavioral school of psychology (classical conditioning). In <strong>1913</strong> he published his article &quot;Psychology as the Behaviorist Views It&quot;, also called &quot;The Behaviourists Manifesto&quot;. In it he outlined the major features of the new psychological school of thought he attempted to promote. &quot;Behaviourism&quot;, as he would call it.</p><p>He described behaviourism as a purely objective experimental branch of natural science, with its main theoretical goal being the prediction and control of behavior. In behaviorist’s opinion, introspection is not essential for psychology. The behaviorist attempts to achieve a unitary scheme of animal response, and therefore recognizes no dividing line between man and animal. </p><button onclick="+'"update('+"'bubble3',"+"'2',"+'false)"'+">Close</button>";
newContentArray[3] = "<p><strong>Watson and Rayner</strong> (1920) conditioned an orphan called Albert B (aka Little Albert) to fear a white rat.</p><p> Prior to the experiment, the child was shown a white rat, a rabbit, a monkey and various masks and showed no fear of any of these stimuli.</p><p> However, what did startle him and cause him to be afraid was if a hammer was struck against a steel bar behind his head. The sudden loud noise would cause &quot;little Albert to burst into tears&quot;.</p><p> When &quot;Little Albert&quot; was just over 11 months old the white rat was presented and seconds later the hammer was struck against the steel bar." + '<img src="http://cdn-4.simplypsychology.org/little-albert.jpg" alt="dog" width="320" style="padding:10px;"></p><p>'+ "This was done 7 times over the next 7 week..  By now &quot;little Albert only had to see the rat and he immediately showed every sign of fear. He would cry (whether or not the hammer was hit against the steel bar) and he would attempt to crawl away.</p><p>Watson and Rayner had shown that classical conditioning could be used to create a phobia. </p><button onclick="+'"update('+"'bubble4'," + "'3',"+'false)"'+">Close</button>";
newContentArray[4] = "<p><strong>Burrhus Frederic Skinner</strong> wrote &quot;The Behaviour of Organisms&quot; (1936)  and properly introduced the concepts of <strong>operant conditioning</strong> and <strong>shaping</strong>, based on the work of Thorndike.</p><p> In contrast to many other behaviourists of the time, Skinner believed that we do have such a thing as a mind, but from scientific point of view it is more productive to study observable behavior rather than internal mental events.</p><p> In his opinion the best way to understand behaviour, was to look at the causes of an action and its consequences. He called this approach <strong>operant conditioning</strong>. </p><p>He based his ideas on Thorndike’s <strong>Law of Effect</strong>, but added a new condition to it - <strong>Reinforcement</strong>. According to it, usually the behaviour that was reinforced tended to be repeated in the future. Likewise, behaviour that lacked reinforcement tended to die-out and be forgotten. </p><p>In his experiment he used a puzzlebox similar to the one Thorndike used, now called Skinner box. </p><p>A hungry rat was placed in the box. After that, one of two tests were carried out. </p><p>The first one involved a lever inside the cage, that, if pressed, would provide some food for the rat. This provided <strong>positive reinforcement</strong> for the rats, and after accidentally activating the lever, they quickly learned to go for it as soon as possible. </p><p>The second test changed the role of the lever. An electric current was run through the cage, placing the rat inside under discomfort. Pressing the lever turned of the current. This provided <strong>negative reinforcement</strong>, which rewarded the subjects for the correct behaviour by removing unpleasant elements. </p><button onclick="+'"update('+"'bubble5',"+"'4',"+'false)"'+">Close</button>";
newContentArray[5] = "<p><strong>Clark Hull’s</strong> (1943) &quot;Principles of Behaviour&quot; was published.</p><p>Hull believed that human behavior is a result of the constant interaction between the organism and its environment. Human is provided the stimuli by the environment and the organism responds in and appropriate manner, all of which is observable. A components that are not observable in this equation, are the changes or adaptatiosn that the organism needs to make in order to survive within its environment. Clark Hull states, &quot;when survival is in jeopardy, the organism is in a state of need (when the biological requirements for survival are not being met) so the organism behaves in a fashion to reduce that need&quot; ( Schultz & Schultz, 1987, p 238). </p><p>Simply, the organism will behave in such a way as to inforce the optimal biological conditions required for survival. </p><button onclick="+'"update('+"'bubble6',"+"'5',"+'false)"'+">Close</button>";
newContentArray[6] = "<p><strong>Albert Bandura</strong> (1963) publishes a book called the &quot;Social Leaning Theory and Personality development&quot; which combines both cognitive and behavioral frameworks.Unlike Skinner, Bandura believed that humans are active information processors and think about the relationship between their behaviour and its consequences. Observational learning could not occur unless cognitive processes were at work. </p><p>This was illustrated during the famous bobo doll experiment (Bandura, 1961). It was a study, conducted to investigate if social behaviors (i.e. aggression) can be acquired by observation and imitation. </p><p>Researchers tested 36 boys and 36 girls from the Stanford University Nursery School aged between 3 to 6 years old. At the beginning of the experiment, children were matched into groups with similar levels of agression in everyday behaviour. </p><p>In the experimental conditions children were individually shown into a room containing toys and played with some potato prints and pictures in a corner for 10 minutes while either: </p><p>24 children (12 boys and 12 girls) watched a male or female model behaving aggressively towards a toy called a 'Bobo doll'. The adults attacked the Bobo doll in a distinctive manner - they used a hammer in some cases, and in others threw the doll in the air and shouted &quot;Pow, Boom&quot;. </p><p>Another 24 children (12 boys and 12 girls) were exposed to a non-aggressive model who played in a quiet and subdued manner for 10 minutes (playing with a tinker toy set and ignoring the bobo-doll). </p><p>The final 24 children (12 boys and 12 girls) were used as a control group and not exposed to any model at all.All the children (including the control group) were subjected to 'mild aggression arousal'. Each child was (separately) taken to a room with relatively attractive toys. As soon as the child started to play with the toys the experimenter told the child that these were the experimenter's very best toys and she had decided to reserve them for the other children. </p><p>The next room contained some aggressive toys and some non-aggressive toys. The non-aggressive toys included a tea set, crayons, three bears and plastic farm animals. The aggressive toys included a mallet and peg board, dart guns, and a 3 foot Bobo doll. </p><p>The child was in the room for 20 minutes and their behavior was observed and rated though a one-way mirror. Observations were made at 5-second intervals therefore giving 240 response units for each child. </p><p>Other behaviors that didn’t imitate that of the model were also recorded e.g. punching the Bobo doll on the nose.</p><button onclick="+'"update('+"'bubble7',"+"'6',"+'false)"'+">Close</button>";
newContentArray[7] = "<p><strong>B.F. Skinner</strong> (1971) published his book Beyond Freedom and Dignity, in which the promoted the idea that free will is an illusion.</p><p>In his book Skinner argued that existing and perpetuated belief in free will and the moral autonomy of the individual (which was referred to as &quot;dignity&quot;) decreases the chances of using objective scientific methods to modify behavior, for the purpose of building a happier and better-organized society. </p><button onclick="+'"update('+"'bubble8',"+"'7',"+'false)"'+">Close</button>";



contentArray[0] = "<p><strong>Ivan  Pavlov</strong> ((1897) published the results of an experiment on conditioning after originally studying digestion in dogs.</p><button onclick="+'"update('+"'bubble1',"+"'0',"+'true)"'+">Expand</button>";
contentArray[1] = "<p><strong>Thorndike</strong> (1905) formalized the &quot;Law of Effect&quot;, which stated that any behaviour that is followed by pleasant consequences is likely to be repeated, and any behaviour followed by unpleasant consequences is likely to be stopped.</p><button onclick="+'"update('+"'bubble2',"+"'1',"+'true)"'+">Expand</button>";
contentArray[2] = "<p>In <strong>1913, John Broadus Watson</strong> published his article &quot;Psychology as the Behaviorist Views It&quot;, through which he launched the behavioral school of psychology (classical conditioning).</p><button onclick="+'"update('+"'bubble3',"+"'2',"+'true)"'+">Expand</button>";
contentArray[3] = "<p>Using behaviorism principles, <strong>Watson and Rayner</strong> (1920) conditioned an orphan called Albert B (aka Little Albert) to fear a white rat.</p><button onclick="+'"update('+"'bubble4',"+"'3',"+'true)"'+">Expand</button>";
contentArray[4] = "<strong>Burrhus Frederic Skinner</strong> wrote &quot;The Behaviour of Organisms&quot; (1936)  and properly introduced the concepts of <strong>operant conditioning</strong> and <strong>shaping</strong>, based on the work of Thorndike.</p><button onclick="+'"update('+"'bubble5',"+"'4',"+'true)"'+">Expand</button>";
contentArray[5] = "<p><strong>Clark Hull’s</strong> (1943) &quot;Principles of Behaviour&quot; was published.</p><button onclick="+'"update('+"'bubble6',"+"'5',"+'true)"'+">Expand</button>";
contentArray[6] = "<p><strong>Albert Bandura</strong> (1963) published a book called the &quot;Social Leaning Theory and Personality development&quot; Also performed the now famous &quot;Bobo doll experiment&quot; which investigated if social behaviors (i.e. aggression) can be acquired by observation and imitation.</p><button onclick="+'"update('+"'bubble7',"+"'6',"+'true)"'+">Expand</button>";
contentArray[7] = "<p><strong>B.F. Skinner</strong> (1971) published his book Beyond Freedom and Dignity, in which the promoted the idea that free will is an illusion.</p><button onclick="+'"update('+"'bubble8',"+"'7',"+'true)"'+">Expand</button>";

